---
title: "team02"
author: "yumin Cho"
date: '2019 11 28 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('C:/RStudy')
options(scipen=100)
library(tibble)
library(ROSE)
library(dplyr)
library(ggplot2)
library(caret)
library(gridExtra)
library(vip)
library(ranger)
library(plotROC)
library(pROC)
f1<-function(cm){
  f1 = 
    2*cm$byClass[[2]]*cm$byClass[[4]]/(cm$byClass[[2]]+cm$byClass[[4]])
  return(f1)
}

```

```{r}
load("test_refined.rda")
```

```{r str}
load("train_pre2.rda")
train_data$RevLineCr<-as.factor(train_data$RevLineCr)
train_data$LowDoc<-as.factor(train_data$LowDoc)
train_data$ApprovalFY<-as.factor(train_data$ApprovalFY)
train_data$NAICS2<-as.factor(train_data$NAICS2)
str(train_data)
```


```{r NAICS2 }
train_data$NAICS2<-gsub("32","31",train_data$NAICS2)
train_data$NAICS2<-gsub("33","31",train_data$NAICS2)
train_data$NAICS2<-gsub("45","44",train_data$NAICS2)
train_data$NAICS2<-gsub("49","48",train_data$NAICS2)
ggplot(train_data) +
  geom_bar(aes(x=NAICS2,fill=outcome),position='fill')
```


```{r industry}
ggplot(train_data) +
  geom_bar(aes(x=industry,fill=outcome),position='fill')
```


```{r DisbursementGross}
ggplot(train_data) +
  geom_boxplot(aes(x=outcome, y=DisbursementGross)) + coord_flip()
ggplot(train_data) +
  geom_boxplot(aes(x=outcome, y=log(DisbursementGross))) + coord_flip()
```

```{r NewExist, UrbanRural}
p1<-ggplot(train_data)+
  geom_bar(aes(x=NewExist, fill=outcome), position="fill") + coord_flip()
p2<-ggplot(train_data)+
  geom_bar(aes(x=UrbanRural, fill=outcome), position="fill") + coord_flip()
grid.arrange(p1, p2, nrow=2)
```

```{r RevLineCr and LowDoc}
p1<-ggplot(train_data)+
  geom_bar(aes(x=RevLineCr, fill=outcome), position="fill") + coord_flip()
p2<-ggplot(train_data)+
  geom_bar(aes(x=LowDoc, fill=outcome), position="fill") + coord_flip()
grid.arrange(p1, p2, nrow=2)
```

```{r RealEstate and Financrisis}
p1<-ggplot(train_data)+
  geom_bar(aes(x=RealEstate, fill=outcome), position="fill") + coord_flip()
p2<-ggplot(train_data)+
  geom_bar(aes(x=Financrisis, fill=outcome), position="fill") + coord_flip()
grid.arrange(p1, p2, nrow=2)
```
```{r dataset split}
set.seed(1234)
train.index <- sample(c(1:NROW(train_data)),NROW(train_data)*0.9)
train.data<-train_data[train.index,]
valid.data<-train_data[-train.index,]

over_df <- 
  ovun.sample(outcome ~ ., 
              data = train.data, 
              method = "over", 
              N = table(train.data$outcome)[[1]]*2)$data
under_df <- 
  ovun.sample(outcome ~ ., 
              data = train.data, 
              method = "under", 
              N = table(train.data$outcome)[[2]]*2)$data
both_df <- 
  ovun.sample(outcome ~ ., 
              data = train.data, 
              method = "both", 
              N = dim(train.data)[1]*2)$data

train.rose<-train.data
train.rose$DisbursementDate<-as.factor(as.character(train.rose$DisbursementDate))
train.rose$ApprovalDate<-as.factor(as.character(train.rose$ApprovalDate))
train.rose$ApprovalFY<-as.factor(train.rose$ApprovalFY)
train.rose$NAICS2<-as.factor(train.rose$NAICS2)
rose_df <- ROSE(outcome ~ ., data = train.rose)$data 
smote_df <- SMOTE(outcome ~ ., data = train.data)

# save(train.data, file="C:/RStudy/train.rda")
# save(valid.data, file="C:/RStudy/valid.rda")
# save(over_df, file="C:/RStudy/over.rda")
# save(under_df, file="C:/RStudy/under.rda")
# save(both_df, file="C:/RStudy/both.rda")
# save(rose_df, file="C:/RStudy/rose.rda")

```

```{r imbalanced class}
load('under.rda')
load('over.rda')
load('both.rda')
load('rose.rda')
load('train.rda')
load('valid.rda')
d=dim(train.data)[2]

rf <- ranger(
	formula = outcome ~ ., 
	data = na.omit(train.data), 
	mtry = sqrt(d), 
	num.trees = 1000, 
	seed = 10, 
	respect.unordered.factors = 'order',
	classification=TRUE, 
	importance = 'impurity')

rf_1 <-ranger(
	formula = outcome ~ ., 
	data = over_df, 
	mtry = sqrt(d), 
	num.trees = 1000, 
	seed = 10, 
	respect.unordered.factors = 'order',
	classification=TRUE, 
	importance = 'impurity')


rf_2 <- ranger(
	formula = outcome ~ ., 
	data = under_df, 
	mtry = sqrt(d), 
	num.trees = 1000, 
	seed = 10, 
	respect.unordered.factors = 'order',
	classification=TRUE, 
	importance = 'impurity')


rf_3 <- ranger(
	formula = outcome ~ ., 
	data = both_df, 
	mtry = sqrt(d), 
	num.trees = 1000, 
	seed = 10, 
	respect.unordered.factors = 'order',
	classification=TRUE, 
	importance = 'impurity')


rf_4 <-ranger(
	formula = outcome ~ ., 
	data = rose_df, 
	mtry = sqrt(d), 
	num.trees = 1000, 
	seed = 10, 
	respect.unordered.factors = 'order',
	classification=TRUE, 
	importance = 'impurity')


prob_pred_rf<-predict(rf,data=na.omit(valid.data), type="response")$predictions
prob_pred_rf_1<-predict(rf_1,data=na.omit(valid.data), type="response")$predictions
prob_pred_rf_2<-predict(rf_2,data=na.omit(valid.data), type="response")$predictions
prob_pred_rf_3<-predict(rf_3,data=na.omit(valid.data), type="response")$predictions
# prob_pred_rf_4<-predict(rf_4,data=na.omit(valid.data), type="response")$predictions

cf = confusionMatrix(na.omit(valid.data)$outcome, prob_pred_rf);f1(cf)
cf_1 = confusionMatrix(na.omit(valid.data)$outcome, prob_pred_rf_1);f1(cf_1)
cf_2 = confusionMatrix(na.omit(valid.data)$outcome, prob_pred_rf_2);f1(cf_2)
cf_3= confusionMatrix(na.omit(valid.data)$outcome, prob_pred_rf_3);f1(cf_3)


# 왜...안돼...?
raw_roc_df  <- tibble(cls = na.omit(valid.data)$outcome, pred=prob_pred_rf, sampling="raw") 
over_roc_df <- tibble(cls =  na.omit(valid.data)$outcome, pred=prob_pred_rf_2, sampling="over")
under_roc_df <- tibble(cls =  na.omit(valid.data)$outcome, pred=prob_pred_rf_1, sampling="under")
both_roc_df <- tibble(cls =  na.omit(valid.data)$outcome, pred=prob_pred_rf_3, sampling="both")
# rose_roc_df <- tibble(cls =  na.omit(valid.data)$outcome, pred=prob_pred_rf_4, sampling="ROSE")

hacide_roc_df <- 
  bind_rows(raw_roc_df, over_roc_df) %>% 
  bind_rows(under_roc_df) %>% 
  bind_rows(both_roc_df) 

head(hacide_roc_df)
hacide_roc_df<-hacide_roc_df[,c(1:3)]
hacide_roc_df$sampling<-as.factor(hacide_roc_df$sampling)
hacide_roc_df$cls<-as.numeric(as.character(hacide_roc_df$cls)) 

ggplot(hacide_roc_df, aes(d = cls, m = pred, color=sampling)) + 
  geom_roc(labels =FALSE)  +
  style_roc() +
  theme(legend.position = "top")

```


```{r rf, eval=FALSE, include=FALSE}
mdl_rf = ranger(outcome ~ . -Id -NAICS -GrAppv -SBA_Appv, data= over_df, 
                mtry = 6, num.trees = 1000, 
                seed = 10, respect.unordered.factors = 'order',
                classification=TRUE, importance = 'impurity')

yhat_rf = predict(mdl_rf, data=na.omit(valid.data), type="response")$predictions
# OOB error
mdl_rf$prediction.error
# feature importance by impurity
head(importance(mdl_rf))
vip(mdl_rf, num_features=25)  # one may not need the vip library
cf = confusionMatrix(na.omit(valid.data)$outcome, yhat_rf);f1(cf)

```


```{r rf1, eval=FALSE, include=FALSE}
# 중요도가 낮은 변수 제거&기존 변수 제거
mdl_rf_1 = ranger(outcome ~ . -Id -NAICS -GrAppv -SBA_Appv -Financrisis -industry -LowDoc -NewExist -City -Bank -ApprovalDate,
                  data=over_df, mtry = 6, num.trees = 1000, 
                seed = 10, respect.unordered.factors = 'order',
                classification=TRUE, importance = 'impurity')

yhat_rf_1 = predict(mdl_rf_1, data=na.omit(valid.data), type="response")$predictions
# OOB error
mdl_rf_1$prediction.error
# feature importance by impurity
head(importance(mdl_rf_1))
vip(mdl_rf_1, num_features=25)  # one may not need the vip library
cf_1 = confusionMatrix(na.omit(valid.data)$outcome, yhat_rf_1);f1(cf_1)

```

```{r rf2, eval=FALSE, include=FALSE}
# 중요도가 낮은 변수 제거&기존 변수 제거
mdl_rf_2 = ranger(outcome ~ . -Id -NAICS -GrAppv -SBA_Appv -Financrisis -industry -LowDoc -NewExist -City -Bank -ApprovalDate -UrbanRural -RevLineCr -RealEstate, data=over_df, 
                mtry = 6, num.trees = 1000, 
                seed = 10, respect.unordered.factors = 'order',
                classification=TRUE, importance = 'impurity')

yhat_rf_2 = predict(mdl_rf_2, data=na.omit(valid.data), type="response")$predictions
# OOB error
mdl_rf_2$prediction.error
# feature importance by impurity
head(importance(mdl_rf_2))
vip(mdl_rf_2, num_features=25)  # one may not need the vip library
cf_2 = confusionMatrix(na.omit(valid.data)$outcome, yhat_rf_2);f1(cf_2)

```

```{r rf3, eval=FALSE, include=FALSE}
mdl_rf_3 = ranger(outcome ~ . -Id -NAICS -GrAppv -SBA_Appv -industry -City -Bank -ApprovalDate -NoEmp -DisbursementDat,
                  data=over_df, mtry = 6, num.trees = 1000, 
                seed = 10, respect.unordered.factors = 'order',
                classification=TRUE, importance = 'impurity')

yhat_rf_3 = predict(mdl_rf_3, data=na.omit(valid.data), type="response")$predictions
# OOB error
mdl_rf_3$prediction.error
# feature importance by impurity
head(importance(mdl_rf_3))
vip(mdl_rf_3, num_features=25)  # one may not need the vip library
cf_3 = confusionMatrix(na.omit(valid.data)$outcome, yhat_rf_3);f1(cf_3)

```

```{r rf4, eval=FALSE, include=FALSE}
mdl_rf_4 = ranger(outcome ~ . -Id -Zip -Bank -City -+DisbursementDate -industry -LowDoc -Financrisis,
                  data=over_df, mtry = 6, num.trees = 1000, 
                seed = 10, respect.unordered.factors = 'order',
                classification=TRUE, importance = 'impurity')

yhat_rf_4 = predict(mdl_rf_4, data=test, type="response")$predictions
# OOB error
mdl_rf_4$prediction.error
# feature importance by impurity
head(importance(mdl_rf_4))
vip(mdl_rf_4, num_features=25)  # one may not need the vip library
cf_4 = confusionMatrix(as.factor(test$outcome), yhat_rf_4);f1(cf_4)

```


